version: "3.9"

services:
  backend:
    image: veerparikh/security-backend
    container_name: security-backend
    ports:
      - "9000:9000"
    depends_on:
      - zap
    environment:
      - ZAP_API_URL=http://zap:8080
    env_file:
      - .env
    restart: unless-stopped

  zap:
    image: zaproxy/zap-stable
    container_name: security-zap
    command: >
      zap.sh -daemon
      -host 0.0.0.0
      -port 8080
      -config api.disablekey=true
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
    ports:
      - "8090:8080"
    restart: unless-stopped
